version: '3'
services:

  mongo:
    container_name: cqrs_app_mongo
    image: mongo:latest
    ports:
      - "27017:27017"

  mysql:
    container_name: cqrs_app_mysql
    image: dnhsoft/mysql-utf8
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
